import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { Link, NavLink, Route, Routes, useLocation } from "react-router-dom";
import "./index.css";

const nav = ["Journey", "Missions", "Archive", "Beyond", "Reading", "Notes", "Contact"];
const destinations = ["Reading", "Field Notes", "Boxing", "Visual Thinking", "Photography & Travel", "Learning Log"];

function Loader() { const [open, setOpen] = useState(!sessionStorage.getItem("observatory_seen")); const reduced = useReducedMotion(); const close = () => { sessionStorage.setItem("observatory_seen", "1"); setOpen(false); }; useEffect(() => { if (!open || reduced) return; const timer = window.setTimeout(close, 2400); return () => window.clearTimeout(timer); }, [open, reduced]); if (!open || reduced) return null; return <motion.aside className="loader" initial={{opacity:1}} exit={{opacity:0}}><div className="loader-chart"><i/><b/><b/><b/><b/></div><p>Receiving signal</p><h2>Turning Data Into Direction</h2><button onClick={close}>Skip intro</button></motion.aside> }
function Header(){return <header><Link className="brand" to="/">Khoi Pham</Link><nav>{nav.map(x=><NavLink key={x} to={`/${x.toLowerCase().replaceAll(" ","")}`}>{x}</NavLink>)}</nav></header>}
function Environment({kind}:{kind:string}){return <div className={`env env-${kind}`} aria-hidden="true"><div/><div/><div/></div>}
function Art({kind}:{kind:string}){return <div className={`art art-${kind}`} aria-label={`${kind} illustration`} role="img"><span/><i/><b/></div>}
function Page({kind,eyebrow,title,copy,children}:{kind:string;eyebrow:string;title:string;copy:string;children?:React.ReactNode}){return <><Environment kind={kind}/><main className="page"><section className="hero"><motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{duration:.6}}><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p>{children}</motion.div><motion.div initial={{opacity:0,rotate:-3}} animate={{opacity:1,rotate:0}} transition={{duration:.8}}><Art kind={kind}/></motion.div></section></main></>}
function Home(){return <Page kind="home" eyebrow="Digital Observatory" title="Turning data into direction." copy="I collect scattered signals, shape them into systems, and turn numbers into stories people can actually use."><Link className="button" to="/journey">Enter the observatory</Link><section className="map"><p className="eyebrow">Navigation chamber</p>{["Journey","Missions","Archive","Beyond"].map((x,i)=><Link key={x} to={`/${x.toLowerCase()}`}><small>0{i+1}</small><strong>{x}</strong></Link>)}</section></Page>}
function Journey(){const [step,setStep]=useState(0);const steps=["Question","Collect","Clean","Analyze","Visualize","Decide"];return <Page kind="journey" eyebrow="Observation Deck" title="Turning questions into direction." copy="An observatory for business questions, evidence, and maps people can actually use."><section className="process"><svg viewBox="0 0 500 180"><path d="M40 142 120 96 200 118 300 56 430 78"/><circle cx={40+step*76} cy={142-step*13} r="10"/></svg><div>{steps.map((s,i)=><button className={i===step?"active":""} onClick={()=>setStep(i)} key={s}>{s}</button>)}</div></section></Page>}
function Beyond(){const [active,setActive]=useState(destinations[0]);return <Page kind="beyond" eyebrow="Personal Study" title="The worlds that shape the way I think." copy="A quieter study room for curiosity, practice, visual thinking and learning beyond the dashboard."><section className="study"><div>{destinations.map(x=><button onClick={()=>setActive(x)} className={active===x?"active":""} key={x}>{x}</button>)}</div><article><h2>{active}</h2><p>{active === "Reading" ? "Books, frameworks and questions kept close to the desk." : "A personal archive entry waiting for the next real field note."}</p>{active==="Reading"&&<Link className="button" to="/reading">Open reading archive</Link>}</article></section></Page>}
function Reading(){const [entered,setEntered]=useState(false);return <Page kind="reading" eyebrow="Observatory Library" title="The Reading Archive" copy="Books that quietly changed the way I think."><button className="button" onClick={()=>setEntered(true)}>Enter the archive</button>{entered&&<section className="book"><Art kind="reading"/><div><p className="eyebrow">Reading / Placeholder</p><h2>The next signal has not been selected yet.</h2><p>Real book data will appear here without invented reflections.</p></div></section>}</Page>}
function Placeholder(){return <Page kind="archive" eyebrow="In transit" title="This room is being rebuilt." copy="The React observatory prototype currently includes Home, Journey, Beyond, and Reading."/>}
function Shell(){const location=useLocation();return <><Header/><AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.45}}><Routes location={location}><Route path="/" element={<Home/>}/><Route path="/journey" element={<Journey/>}/><Route path="/beyond" element={<Beyond/>}/><Route path="/reading" element={<Reading/>}/><Route path="*" element={<Placeholder/>}/></Routes></motion.div></AnimatePresence><Loader/></>}
export default Shell;
